version: '3.7'

services:
  server:
    container_name: ${SERVER_HOST}
    init: true
    command: /bin/ash
    build:
      context: ${DIR}/server
      dockerfile: Dockerfile
    volumes:
      - ${DIR}/server:/server
      - ${DIR}/conf/ssl.dev:/server/ssl:ro
    env_file:
      - ${DIR}/conf/hosts.env
    networks:
      - backend
      - frontend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - ${DB_HOST}
      - ${REDIS_HOST}
  client:
    container_name: ${CLIENT_HOST}
    stdin_open: true
    command: /bin/ash
    build:
      context: ${DIR}/client
      dockerfile: Dockerfile
    volumes:
      - ${DIR}/client:/client
    env_file:
      - ${DIR}/conf/hosts.env
    networks:
      - frontend
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
  db:
    image: mongo:4
    container_name: ${DB_HOST}
    restart: always
    volumes:
      - ${DIR}/db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ${DIR}/db/data/dev:/data/db
    env_file:
      - ${DIR}/conf/hosts.env
    networks:
      - backend
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis:
    image: redis:5-alpine
    container_name: ${REDIS_HOST}
    env_file:
      - ${DIR}/conf/hosts.env
    networks:
      - backend
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge